export const russian = {
    lang: "ru",
      category:{
        description: "описание",
        company: "о компании",
        missions: "миссии",
        launches: "запуски",
        rockets: "ракеты",
        capsules: "капсулы",
        dragons: "crew dragon",
        landpads: "пусковые площадки",
        sourse: "исходники",
        navigation: "навигация",
      },
      helpers:{
        whatisit: "что это?",
        all: "все",
        past: "прошедшие",
        upcoming: "предстоящие",
        contacts: "контакты",
        total: "все",
        license: "лицензия"
      },
      description:{
        main: "Визуализация данных из SpaceX RestApi.",
        description: "Описание всех данных в формате JSON.",
        missions: "Информация о всех миссиях SpaceX.",
        launches: "Информация о запусках SpaceX.",
        rockets: "ракеты разработанные SpaceX.",
        capsules: "Все капсулы участвующие в миссиях",
        dragons: "американский многоразовый пилотируемый космический корабль компании SpaceX, разработанный по заказу НАСА",
        landpads: "посадочная площадка SpaceX",
       },
       card:{
         name:"имя",
         status:"статус",
         totalLandings: "всего запусков",
         successfulLandings:"всего успешных запусков",
         landingType: "тип посадки",
         region: "регион",
         location: "локация",
         coordinates: "координаты",
         description: "показать описание",
         chartShow: "показать данные в виде графика",
         chartClose: "скрыть данные в виде графика",
         humans: "сотрудников",
         cto: "Технический директор",
         ceo: "Генеральный директор",
         coo: "Главный операционный директор",
         DateOfFoundation:"Компания основана в",
         year: "год",
         founder: "Основатель",
         headquarters: "Штаб-квартира",
         totalEmployees: "Количество сотрудников",
         totalVehicles: "количество едениц техники в операции",
         version: "версия",
        }
}

export const english = {
    lang: "en",
      category:{
        description: "description",
        company: "about company",
        missions: "missions",
        launches: "launches",
        rockets: "rockets",
        capsules: "capsules",
        dragons: "crew dragon",
        landpads: "landpads",
        sourse: "sourse",
        navigation: "navigation",
        license: "license"
      },
      helpers:{
        whatisit: "what is it?",
        all: "all",
        past: "past",
        upcoming: "upcoming",
        contacts: "contacts",
        total: "total",
      },
      description:{
        main: "Data visualization from SpaceX RestAPI.",
        description: "Description of all data in JSON format.",
        missions: "Information about all SpaceX missions.",
        launches: "Information about SpaceX launches.",
        rockets: "rockets developed by SpaceX.",
        capsules: "All capsules participating in the missions",
        dragons: "the American reusable manned spacecraft of the SpaceX company, developed by order of NASA",
        landpads: "SpaceX landing pad",
      },
      card:{
        name:"name",
        status:"status",
        totalLandings: "total landings",
        successfulLandings:"total successful landings",
        landingType: "landing type",
        region: "region",
        location: "location",
        coordinates: "coordinates",
        description: "show a description",
        chartShow: "show this data as a graph",
        chartClose: "hide data in the graph view",
        humans: "employees",
        cto: "Chief technology officer",
        ceo: "Chief executive officer",
        coo: "Chief operating officer",
        DateOfFoundation: "Date of foundation",
        year: "year",
        founder: "Founder",
        headquarters: "Headquarters",
        totalEmployees: "Total employees",
        totalVehicles: "total Vehicles",
        version: "version",
        rocket: "rocket",
      }
}