export const russian = {
    lang: "ru",
      category:{
        info: "информация",
        description: "описание",
        api: "о Api",
        company: "о компании",
        missions: "миссии",
        launches: "запуски",
        rockets: "ракеты",
        capsules: "капсулы",
        dragons: "crew dragon",
        landpads: "пусковые площадки",
        sourse: "исходники",
        navigation: "навигация",
        license: "лицензия",
        myGitHub: "мой GitHub",
        repository: "репозиторий этого проекта на GitHub"
      },
      helpers:{
        whatisit: "что это?",
        all: "все",
        past: "прошедшие",
        upcoming: "предстоящие",
        contacts: "контакты",
        total: "все",
        description:"показать описание",
        copied: "скопировано"
      },
      description:{
        main: "Визуализация данных из SpaceX RestApi.",
        description: "Описание всех данных в формате JSON.",
        missions: "Информация о всех миссиях SpaceX.",
        launches: "Информация о запусках SpaceX.",
        rockets: "ракеты разработанные SpaceX.",
        capsules: "Все капсулы участвующие в миссиях",
        dragons: "американский многоразовый пилотируемый космический корабль компании SpaceX, разработанный по заказу НАСА",
        landpads: "посадочная площадка SpaceX",
       },
       card:{
         name:"имя",
         status:"статус",
         totalLandings: "всего запусков",
         successfulLandings:"всего успешных запусков",
         landingType: "тип посадки",
         region: "регион",
         location: "локация",
         coordinates: "координаты",
         description: "показать описание",
         chartShow: "показать данные в виде графика",
         chartClose: "скрыть данные в виде графика",
         humans: "сотрудников",
         cto: "Технический директор",
         ceo: "Генеральный директор",
         coo: "Главный операционный директор",
         DateOfFoundation:"Компания основана в",
         year: "год",
         founder: "Основатель",
         headquarters: "Штаб-квартира",
         totalEmployees: "Количество сотрудников",
         totalVehicles: "количество едениц техники в операции",
         version: "версия",
         active:"Активная",
         mass:"масса",
         fireTime:"общее время горения",
         diameter: "диаметр",
         height: "высота",
         fuelQuantity: "количество топлива",
         preSuccessfulLandings:"процент успешных запусков",
         costPerLaunch:"стоимость за запуск",
         dateFirstFlight: "дата первого вылета",
         thrustVacuum:"тяга в вакууме",
         serialNumber: "серийный номер",
         readWiki: "прочитайте статью на википедии",
         flight:"вылет",
         missions:"миссии",
         date:"дата",
         type:"тип",
         reuseCount: "Количество повторного использования",
         indefiniteDate: "неопределённая дата",
         noMissions: "нет миссий",
         landingCount: "количество высадок",
         crewCapacity: "вместимость экипажа",
         cargoBayHeight: "высота грузового отсека",
         startWeight: "стартовый вес полезной нагрузки"
        }
      }

export const english = {
    lang: "en",
      category:{
        info: "info",
        description: "description",
        api: "about Api",
        company: "about company",
        missions: "missions",
        launches: "launches",
        rockets: "rockets",
        capsules: "capsules",
        dragons: "crew dragon",
        landpads: "landpads",
        sourse: "sourse",
        navigation: "navigation",
        license: "license",
        myGitHub: "my GitHub",
        repository: "repository of this project on GitHub"
      },
      helpers:{
        whatisit: "what is it?",
        all: "all",
        past: "past",
        upcoming: "upcoming",
        contacts: "contacts",
        total: "total",
        description:"show а descripton",
        copied: "copied"
      },
      description:{
        main: "Data visualization from SpaceX RestAPI.",
        description: "Description of all data in JSON format.",
        missions: "Information about all SpaceX missions.",
        launches: "Information about SpaceX launches.",
        rockets: "rockets developed by SpaceX.",
        capsules: "All capsules participating in the missions",
        dragons: "the American reusable manned spacecraft of the SpaceX company, developed by order of NASA",
        landpads: "SpaceX landing pad",
      },
      card:{
        name:"name",
        status:"status",
        totalLandings: "total landings",
        successfulLandings:"total successful landings",
        landingType: "landing type",
        region: "region",
        location: "location",
        coordinates: "coordinates",
        description: "show a description",
        chartShow: "show this data as a graph",
        chartClose: "hide data in the graph view",
        humans: "employees",
        cto: "Chief technology officer",
        ceo: "Chief executive officer",
        coo: "Chief operating officer",
        DateOfFoundation: "Date of foundation",
        year: "year",
        founder: "Founder",
        headquarters: "Headquarters",
        totalEmployees: "Total employees",
        totalVehicles: "total Vehicles",
        version: "version",
        rocket: "rocket",
        active:"Active",
        mass:"mass",
        fireTime:"total fuel burn time",
        diameter: "diameter",
        height: "height",
        fuelQuantity: "fuel quantity",
        preSuccessfulLandings:"percentage of successful launches",
        costPerLaunch:"cost per launch",
        dateFirstFlight: "first launch date",
        thrustVacuum: "vacuum thrust",
        serialNumber: "serial number",
        readWiki: "read the article on wikipedia",
        flight:"flight",
        missions:"missions",
        date:"date",
        type:"type",
        indefiniteDate: "indefinite date",
        reuseCount: "reuse count",
        noMissions: "no missions",
        landingCount: "landing count",
        crewCapacity: "crew capacity",
        cargoBayHeight: "cargo bay height",
        startWeight: "starting weight of the payload",
      }
}